"use strict"

const Command = require ("../command");

const quotes = [
            "Towelie",
            "Tweek Tweak",
            "Stephen Stotch",
            "Jesus Christ",
            "Scott Tenorman",
            "Stan Marsh",
            "Eric Cartman",
            "ManBearPig",
            "6th Grader",
            "Kenny McCormick",
            "Jerome 'Chef' McElroy",
            "Kyle Broflovski",
            "Saddam Hussein",
            "Wendy Testaburger",
            "PC Principal",
            "Craig Tucker",
            "Satan",
            "Underpants Gnome",
            "Mr. Kitty",
            "Butters Stotch",
            "Dogpoo",
            "Clyde Donovan",
            "Mecha Streisand",
            "Bebe Stevens",
            "Pip Pirrup",
            "Cthulhu",
            "Randy Marsh",
            "One Rat",
            "Damien",
            "Liane Cartman",
            "A.W.E.S.O.M.-O 4000",
            "Tricia",
            "Nelly",
            "GS-401",
            "Shub-Niggurath",
            "Nathan",
            "Mimsy",
            "Classi",
            "Scuzzlebutt",
            "Terrance",
            "Phillip",
            "Barbra Streisand",
            "Santa Claus",
            "Sheila Broflovski",
            "Shelly Marsh",
            "Gerald Broflovski",
            "Scott Malkinson",
            "Russel Crowe",
            "Bat Dad",
            "Brimmy",
            "Rob Schneider",
            "Selena Gomez",
            "Mitch Connor",
            "Dougie O'Connel",
            "Mr. Mackey",
            "Sexual Harassment Panda",
            "Kanye West",
            "Mr. Garrison",
            "Strong Woman",
            "Mr. Hankey",
            "Mr. Mackey",
            "Henrietta",
            "Firkle",
            "Michael",
            "Pete",
            "Kyle Schwartz",
            "King Douchebag",
            "Brimmy",
            "Jared Fogle",
            "Jenkins",
            "Dildo Shwaggins",
            "Mr. Slave",
            "Tardicaca Shark",
            "Marklar",
            "Filmore",
            "Ike Broflovski",
            "Penis Mouse",
            "Blanket",
            "Corey Haim",
            "Bradley Biggle",
            "Reality",
            "Iggy Azalea",
            "Reality",
            "Mr. Derp",
            "Peter Mullen",
            "Dr. Nelson",
            "Snooki",
            "Bono",
            "Ben Assfleck",
            "Heroin Dragon",
            "Scott",
            "Ugly Bob",
        ];

const versus = new Command("versus", "fight", "js", 0, "versus", "command", 0, false, null, function(client, message, guildDoc) {
        const random1 = Math.floor(Math.random() * quotes.length);
        const random2 = Math.floor(Math.random() * quotes.length);
        message.channel.send("**Who would win:** " + quotes[random1] + " **or** " + quotes[random2] + "?").then(function () {
            if (quotes[random1] == quotes[random2]) {
                message.channel.send("*This wasn't meant to happen but here we are...*")
            }
        });
});

module.exports = versus;

