import { Schema } from "mongoose";

import GuildScriptSchema from "./guildScript";
import GuildScriptPermsSchema from "./guildScriptPerms";

const memberPermSchema = new Schema({

  member_id: { type: String, required: true },
  list: [String]
}, {
  _id: false
});

const GuildSchema = new Schema({

  // Id generated by mongo, this is here so I remember it exists.
  // _id: ObjectId,

  discord_id: { type: String, required: true, unique: true },
  prefix: { type: String, default: "-" },
  premium: { type: Boolean, default: false },
  member_perms: [memberPermSchema],
  script_perms: GuildScriptPermsSchema,
  scripts: [GuildScriptSchema]
});

export default GuildSchema;
