"use strict";

const mongoose = require("mongoose");

const GuildScriptSchema = require("./guildScript"); 

const memberPermSchema = new mongoose.Schema({

  member_id: { type: String, required: true },
  list: [ String ]
}, {
  _id: false
});

const GuildSchema = new mongoose.Schema({

  // Id generated by mongo, this is here so I remember it exists.
  // _id: ObjectId,

  discord_id: { type: String, required: true, unique: true },
  prefix: { type: String, default: "-" },
  premium: { type: Boolean, default: false },
  member_perms: [ memberPermSchema ],
  script_perms: scriptPermSchema,
  scripts: [ guildScriptSchema ]
});

module.exports = GuildSchema;
