"use strict";

const mongoose = require("mongoose");

const socialSchema = new mongoose.Schema({

  name: { type: String, required: true },
  icon: { type: String, required: true },
  url: { type: String, required: true }
}, {
  _id: false
});

const moduleSchema = new mongoose.Schema({

  name: { type: String, required: true },
  enabled: { type: Boolean, default: false },
  content: [ String ]
}, {
  _id: false
});

const colourSchema = new mongoose.Schema({

  progress: { type: String, default: "#42f4e5" },
  level: { type: String, default: "#42f4e5" },
  rank: { type: String, default: "#42f4e5" },
  name: { type: String, default: "#42f4e5" }
}, {
  _id: false
});

const UserSchema = new mongoose.Schema({

  // Id generated by mongo, this is here so I remember it exists.
  // _id: ObjectId,

  discord_id: { type: String, required: true, unique: true },

  banner: { type: String, default: "https://media.discordapp.net/attachments/379432139856412682/462737165806338058/abstract2.png" },
  bio: { type: String, default: "This person is very mysterious." },
  socials: [ socialSchema ],
  modules: [ moduleSchema ],
  colours: colourSchema,

  admin: { type: Boolean, default: false },
  verified: { type: Boolean, default: false },
  developer: { type: Boolean, default: false },
  tier: { type: String, default: "free" },
  premium: [ String ],

  xp: { type: Number, default: 0 },
  shits: { type: Number, default: 0 },
  trophies: [ String ],

  likes: [ Schema.Types.ObjectId ]
});

module.exports = UserSchema;
